routes/book.py
from flask import Blueprint, g, escape, session, redirect, render_template, request, jsonify, Response
from app import DAO

from Controllers.UserManager import UserManager
from Controllers.BookManager import BookManager

book_view = Blueprint('book_routes', __name__, template_folder='/templates')

book_manager = BookManager(DAO)
user_manager = UserManager(DAO)



@book_view.route('/', defaults={'id': None})
@book_view.route('/<int:id>')
def home(id):
	user_manager.user.set_session(session, g)

	if id != None:
		b = book_manager.getBook(id)

		print('----------------------------')
		print(b)

		user_books={}
		if user_manager.user.isLoggedIn():
			user_books = book_manager.getReserverdBooksByUser(user_id=user_manager.user.uid())['user_books'].split(',')
		
		if b and len(b) <1:
			return render_template('book_view.html', error="No book found!")

		return render_template("book_view.html", books=b, g=g, user_books=user_books)
	else:
		b = book_manager.list()

		user_books=[]
		if user_manager.user.isLoggedIn():
			reserved_books = book_manager.getReserverdBooksByUser(user_id=user_manager.user.uid())
			
			if reserved_books is not None:
				user_books = reserved_books['user_books'].split(',')
		
		print("---------------------------------------")
		print(user_books)

		if b and len(b) <1:
			return render_template('books.html', error="No books found!")
	
		return render_template("books.html", books=b, g=g, user_books=user_books)


	return render_template("books.html", books=b, g=g)


@book_view.route('/add/<id>', methods=['GET'])
@user_manager.user.login_required
def add(id):
	user_id = user_manager.user.uid()
	book_manager.reserve(user_id, id)

	b = book_manager.list()
	user_manager.user.set_session(session, g)
	
	return render_template("books.html", msg="Book reserved", books=b, g=g)


@book_view.route('/search', methods=['GET'])
def search():
	user_manager.user.set_session(session, g)

	if "keyword" not in request.args:
		return render_template("search.html")

	keyword = request.args["keyword"]

	if len(keyword)<1:
		return redirect('/books')

	d=book_manager.search(keyword)

	if len(d) >0:
		return render_template("books.html", search=True, books=d, count=len(d), keyword=escape(keyword), g=g)

	return render_template('books.html', error="No books found!", keyword=escape(keyword))

routes/user.py
from flask import Blueprint, g, escape, session, redirect, render_template, request, jsonify, Response, flash,url_for
from app import DAO  # Data object model that has been initialized with the app 
from Misc.functions import *

from Controllers.UserManager import UserManager


#  Blueprint in Flask is a way to organize your application into modular components
# A new Blueprint instance named user_view is created.
# This blueprint is associated with the name 'user_routes'.
# The __name__ variable helps Flask to know where this blueprint is defined.
# The template_folder='/templates' argument tells Flask to look for templates in the /templates directory when rendering views associated with this blueprint.
user_view = Blueprint('user_routes', __name__, template_folder='/templates')  

user_manager = UserManager(DAO)

@user_view.route('/', methods=['GET'])
def home():
	g.bg = 1

	user_manager.user.set_session(session, g)
	print(g.user)

	return render_template('home.html', g=g)


@user_view.route('/signin', methods=['GET', 'POST'])
@user_manager.user.redirect_if_login
def signin():
	if request.method == 'POST':
		_form = request.form
		email = str(_form["email"])
		password = str(_form["password"])

		if len(email)<1 or len(password)<1:
			return render_template('signin.html', error="Email and password are required")

		d = user_manager.signin(email, hash(password))

		if d and len(d)>0:
			session['user'] = int(d['id'])

			return redirect("/")

		return render_template('signin.html', error="Email or password incorrect")


	return render_template('signin.html')


@user_view.route('/signup', methods=['GET', 'POST'])
@user_manager.user.redirect_if_login
def signup():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')
        bio = request.form.get('bio')
        mobile = request.form.get('mobile')

        if len(name) < 1 or len(email) < 1 or len(password) < 1 or len(bio) < 1 or len(mobile) < 1:
            return render_template('signup.html', error="All fields are required")

        new_user = user_manager.signup(name, email, hash(password), bio, mobile)

        if new_user == "already_exists":
            return render_template('signup.html', error="User already exists with this email")

        return render_template('signup.html', msg="You've been registered!")

    return render_template('signin.html')


@user_view.route('/signout/', methods=['GET'])
@user_manager.user.login_required
def signout():
	user_manager.signout()

	return redirect("/", code=302)

@user_view.route('/user/', methods=['GET'])
@user_manager.user.login_required
def show_user(id=None):
	user_manager.user.set_session(session, g)
	
	if id is None:
		id = int(user_manager.user.uid())

	d = user_manager.get(id)
	mybooks = user_manager.getBooksList(id)

	return render_template("profile.html", user=d, books=mybooks, g=g)

@user_view.route('/user/', methods=['POST'])
@user_manager.user.login_required
def update():
	user_manager.user.set_session(session, g)
	
	_form = request.form
	name = str(_form["name"])
	email = str(_form["email"])
	password = str(_form["password"])
	bio = str(_form["bio"])

	user_manager.update(name, email, hash(password), bio, user_manager.user.uid())

	flash('Your info has been updated!')
	return redirect(url_for('user_routes.show_user'))

templates/book_view.html
{%extends "/shared/layout.html" %}

{% block title %}Book - {{books['name']}} {% endblock %}

{% block content %}
<div class="container">
    <div style="width:100%; margin-top: 3em;margin-bottom: 2em;">
        {% if msg %}
            <div class="alert alert-success">{{msg}}</div>
        {% endif %}
        <form action="/books/search" method="GET">
          <div class="form-group">
            <div style="width: 100%">
            <div style="width: 90%; display: inline-block;">
            <input type="search" name="keyword" autofocus class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{keyword}}" placeholder="Search for books...">
            </div>
            <button type="submit" style="margin-left: 5px;" class="btn btn-primary">Search</button>
            </div>
          </div>
        </form>
    </div>

    {% if books %}
            <div class="row">
                <div class="col-md-12">
                    <div class="card  book" style="width:100%">
                        <div class="card-body">
                            <div class="row">
                            <div class="col-md-5">
                                <img src="/static/images/bg.jpg" style="height: 250px; width: auto; 
                                margin: 0 auto;
                                display: block;" class="card-img-top" alt="{{books[1]}}">
                                <a href="/books/add/{{books['id']}}" class="btn btn-outline-warning ml-3 mt-3  {{ 'disabled' if str(books['id']) in user_books else '' }}"><i class="bi bi-journal-plus"></i> {{ 'Added' if str(books['id']) in user_books else 'Add' }}</a>

                                <div class="platforms mt-3 ml-3">
                                    <h4 class="font-weight-light" style="margin-bottom: 0;">Avaliable On:</h4>
                                    <div style="font-size: 2.1em;">
                                        <i class="bi bi-xbox" style="color: green;"></i>
                                        <i class="bi bi-youtube ml-2" style="color: red;"></i>
                                        <i class="bi bi-windows ml-2" style="color: rgb(39, 144, 185);"></i>
                                        <i class="bi bi-github ml-2" style=""></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h2>{{books['name']}}</h2>
                                {% if books['availability'] < 1 %}
                                <span class="badge badge-warning" style="margin-bottom: 5px;">Assigned</span>
                                {% endif %}
                                <p class="card-text">{{books['desc']}}</p>
                                <p class="card-text font-weight-light"><b>Author:</b> {{books['author']}}</p>
            
                                <p class="card-text">
                                <span class="badge badge-{{ 'primary' if books['count'] > 0 else 'secondary' }}" style="margin-bottom: 5px;">
                                    {% if books['count'] > 0%}
                                        Books Left: {{books['count']}}
                                    {% else %}
                                        All gone
                                    {% endif %}
                                </span>
                                </p>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% else %}
            <div class="card bwrapper">
                <div class="card-body">
                    <div class="text-center mb-4" style="
                    margin-top: 21px !important;"><i class="text-center mt-4 bi-book" style="
                        font-size: 6em; "></i></div>
                    <p class="text-center mb-4">No Book Found!</p>
                </div>
            </div>
        {% endif %}	
</div>
{% endblock %}

templates/books.html
{%extends "/shared/layout.html" %}

{% block title %}Books{% endblock %}

{% block head %}
	{{ super() }}

    <link rel="stylesheet" href="/static/home.css" />
{% endblock %}

{% block content %}
	<div class="container h-75">	
		<div style="width:100%; margin-top: 3em;">
			{% if msg %}
				<div class="alert alert-success">{{msg}}</div>
			{% endif %}
			<form action="/books/search" method="GET">
			  <div class="form-group">
			    <div style="width: 100%">
			    <div style="width: 90%; display: inline-block;">
			    <input type="search" name="keyword" autofocus class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="{{keyword}}" placeholder="Search for books...">
			    </div>
				<button type="submit" style="margin-left: 5px;" class="btn btn-primary">Search</button>
			    </div>
			  </div>
			</form>
		</div>

		<div style="width:100%; margin-top: 3em;">
			{% if books %}
				{% if search %}
				<h4>Search Found ({{count}})</h4>
				{% endif %}
				{% for book in books %}
				<div class="card book">
				  <img src="/static/images/bg.jpg" class="card-img-top" alt="{{book[1]}}">
				  <div class="card-body">
				    <h5 class="card-title"><a href="/books/{{book['id']}}">{{book['name']}}</a></h5>
				    {% if book['availability'] < 1 %}
				    	<span class="badge badge-warning" style="margin-bottom: 5px;">Assigned</span>
				    {% endif %}
				    <p class="card-text bookdesc">{{book['desc']}}</p>

				    <p class="card-text">
				    <span class="badge badge-{{ 'primary' if book['count'] > 0 else 'secondary' }}" style="margin-bottom: 5px;">
				    	{% if book['count'] > 0%}
				    	  Books Left: {{book['count']}}
				    	{% else %}
				    	  All gone
				    	{% endif %}
				    </span>
					</p>

				    {% if book['count'] > 0 %}
				    <a href="/books/add/{{book['id']}}" {{ 'disabled' if user_books!=None and str(book['id']) in user_books else '' }} class="btn btn-outline-warning {{ 'disabled' if str(book['id']) in user_books else '' }}"><i class="bi bi-journal-plus"></i> {{ 'Added' if str(book['id']) in user_books else 'Add' }}</a>
				    {% endif %}
				  </div>
				</div>
				{% endfor %}
			{% else %}
				<h4>No Books Found!</h4>
				<p>Please contact the librarian</p>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/home.html
{%extends "/shared/layout.html" %}

{% block title %}Home{% endblock %}

{% block head %}
	{{ super() }}

    <link rel="stylesheet" href="/static/home.css" />
{% endblock %}

{% block content %}
	<div class="container d-flex h-75">
	    <div class="row justify-content-center align-self-center welcome">
	    	<h3>WELCOME</h3>
			<div style="width:100%">
			<form action="/books/search" method="GET">
			  <div class="form-group">
			    <label for="exampleInputEmail1">Search</label>
			    <input type="search" autocomplete="false" name="keyword" autofocus class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Search for books...">
			    <small id="emailHelp" class="form-text text-muted">Available books will be shown to members.</small>
			  </div>
			  <button type="submit" class="btn btn-primary">Search</button>
			</form>
			</div>
	    </div>
	</div>
{% endblock %}

templates/profile.html
{%extends "/shared/layout.html" %}

{% block title %}Profile - {{user['name']}} {% endblock %}

{% block content %}
	<div class="profile container">
		{% with messages = get_flashed_messages() %}
			{% if messages %}
				<div class="alert alert-success">
					{% for message in messages %}
						<span>{{ message }}</span>
					{% endfor %}
				</div>
			{% endif %}
		{% endwith %}
		<div class="">

            <div class="card-body">
                <div class="row d-flex justify-content-between">
                    <div class="col-md-4 pt-4 card" style="height: fit-content;">
                        <div class="card-body">
                            <div class="form-group">
                                <div class="profile-pic-div m-auto">
                                    <img src="/static/images/avatar.jpg" id="photo">
                                    <!-- <input type="file" id="file">
                                    <label for="file" id="uploadBtn" style="display: none;">Choose Photo</label> -->
									<div class="text-center mt-4">{{user['name']}}</div>
                                </div>
                            </div>
                            <hr>
                            <p class="lead">
                                {{user['bio']}}
                            </p>
							<hr/>
							<p class="lead">Joined: <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-activity" viewBox="0 0 16 16">
								<path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z"/>
							  </svg> {{ago(user['created_at'])}}</p>
                        </div>
                    </div>
                    <div class="card col-md-7 mwrapper">

						<ul class="nav nav-tabs" id="myTab" role="tablist">
							<li class="nav-item">
							  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Your Books</a>
							</li>
							<li class="nav-item">
							  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
							</li>
						  </ul>

						  <div class="col-md-12 ">
							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
								<div class="">
									{% if books %}
										<!-- <h2 class="text-center mt-4" style="margin-bottom: 0.5em;">Your Books</h2> -->
										<div class="text-center mb-4 mt-4"><i class="text-center mt-4 bi-book" style="
											font-size: 6em; "></i></div>
										{% for book in books %}
											<div class="card book">
												<img src="/static/images/bg.jpg" class="card-img-top" alt="{{book[1]}}">
												<div class="card-body">
				    								<h5 class="card-title"><a href="/books/{{book['id']}}">{{book['name']}}</a></h5>
													{% if book['availability'] < 1 %}
														<span class="badge badge-warning" style="margin-bottom: 5px;">Assigned</span>
													{% endif %}
													<!-- <p class="card-text bookdesc">{{book['desc']}}</p> -->

													<p class="card-text">Author: <span class="font-weight-light">{{book['author']}}</span></p>
												</div>
											</div>
										{% endfor %}
										{% else %}
											<div class="card bwrapper">
												<div class="card-body">
													<h4 class="text-center mt-4">Manage Books</h4>
													<div class="text-center mb-4" style="margin-top: 21px !important;">
														<!-- <i class="text-center mt-4 bi-book" style="font-size: 6em; "></i> -->
														<svg xmlns="http://www.w3.org/2000/svg" width="6em" height="6em" fill="currentColor" class="bi bi-activity" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z"/>
														</svg>
													</div>
													<p class="text-center mb-4">No Books You Reserved!</p>
												</div>
											</div>
										{% endif %}	
										</div>
								</div>
								<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
									<div class="card-body">
										<h4 class="text-center mt-4">Manage Account</h4>
										<p class="text-center mb-4">One Account For Everything</p>

										<form method="POST" action="{{url_for('user_routes.update')}}">
											<div class="row">
												<div class="col-sm-12">
													<div class="form-group">
														<label for="inputFirstName" class="form-label">Your Name</label>
														<input type="text" placeholder="Enter Your Name" name="name" value="{{user['name']}}" class="form-control" id="inputFirstName">
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-sm-6">
													<div class="form-group">
													<label for="inputEmail3" class="form-label">Email</label>
													<input type="email" placeholder="Email" value="{{user['email']}}" name="email" class="form-control" id="inputEmail3">
													</div>
												</div>
												<div class="col-sm-6">
														<div class="form-group">
														<label for="password" class="form-label">Password</label>
														<input type="password" placeholder="Password" class="form-control" id="password" name="password">
													</div>
												</div>
											</div>
											<div class="form-group">
												<label for="inpBio" class="form-label">Bio</label>
												<textarea class="form-control" rows="3" name="bio" id="inpBio">{{user['bio']}}</textarea>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-block btn-primary">Save Changes</button>
											</div>
										</form>	
									</div>
								</div>
							</div>
						  </div>

                    </div>

                </div>
            </form>
        </div>
	</div>
{% endblock %}

templates/signin.html
{%extends "/shared/layout.html" %}

{% block title %}Signin{% endblock %}

{% block head %}
	{{ super() }}

    <link rel="stylesheet" href="/static/home.css" />
{% endblock %}

{% block content %}
	<div class="container d-flex h-75">
	    <div class="row justify-content-center align-self-center welcome">
			<h4>SIGNIN</h4>

			<div style="width:90%">
				{% if error %}
					<div class="alert alert-danger">
						{{error}}
					</div>
				{% endif %}
				<form action="{{url_for('user_routes.signin')}}" method="POST">
					<div class="form-group">
						<label for="exampleInputEmail1">Email address</label>
						<input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
						<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">Password</label>
						<input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
					</div>

					<div class="form-group">
						<a href="/signup">Join us now!</a>
					</div>

					<button type="submit" class="btn btn-primary">Signin</button>
					<!-- <a style="margin-left: 10px" href="/signup">Or join us now!</a> -->
				</form>
			</div>
	    </div>
	</div>
{% endblock %}

templates/signup.html
{% extends "/shared/layout.html" %}

{% block title %}Signup{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/home.css" />
{% endblock %}

{% block content %}
    <div class="container d-flex h-75">
        <div class="row justify-content-center align-self-center welcome">
            <h4>SIGNUP</h4>
            <div style="width:90%">
                {% if msg %}
                    <div class="alert alert-success">
                        {{msg}}
                    </div>
                {% endif %}
                {% if error %}
                    <div class="alert alert-danger">
                        {{error}}
                    </div>
                {% endif %}
                <form action="{{ url_for('user_routes.signup') }}" method="POST">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" aria-describedby="name" placeholder="Your name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email address">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label for="bio">Bio</label>
                        <textarea class="form-control" id="bio" name="bio" rows="3" placeholder="Tell us about yourself"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="mobile">Mobile Number</label>
                        <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Enter your mobile number">
                    </div>
                    <button type="submit" class="btn btn-primary">Signup</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/welcome.html
welcome.html