routes/admin.py
from flask import Blueprint, g, escape, session, redirect, render_template, request, flash ,  jsonify, Response, url_for
from app import DAO
from Misc.functions import *

from Controllers.AdminManager import AdminManager
from Controllers.BookManager import BookManager
from Controllers.UserManager import UserManager

admin_view = Blueprint('admin_routes', __name__, template_folder='/templates/')

book_manager = BookManager(DAO)
user_manager = UserManager(DAO)
admin_manager = AdminManager(DAO)


@admin_view.route('/', methods=['GET'])
# @admin_manager.admin.login_required
def home():
	g.bg = 1
	admin_manager.admin.set_session(session, g)

	return render_template('admin/home.html', g=g)



@admin_view.route('/signin/', methods=['GET', 'POST'])
@admin_manager.admin.redirect_if_login
def signin():
	if request.method == 'POST':
		_form = request.form
		email = str(_form["email"])
		password = str(_form["password"])

		if len(email)<1 or len(password)<1:
			return render_template('admin/signin.html', error="Email and password are required")

		d = admin_manager.signin(email, hash(password))

		if d and len(d)>0:
			session['admin'] = int(d["id"])

			return redirect("/admin")

		return render_template('admin/signin.html', error="Email or password incorrect")

	return render_template('/admin/signin.html')


@admin_view.route('/signup/', methods=['GET', 'POST'])
@admin_manager.admin.redirect_if_login
def signup():

	if request.method == 'POST':
		email = request.form.get('email')
		password = request.form.get('password')

		if  len(email) < 1 or len(password) < 1 :
			return render_template('admin/signup.html', error="All fields are required")

		new_admin = admin_manager.signup( email, hash(password))

		if new_admin == "already_exists":
			return render_template('admin/signup.html', error="User already exists with this email")

		return render_template('admin/signin.html', msg="You've been registered!")

	return render_template('admin/signup.html')


@admin_view.route('/signout/', methods=['GET'])
@admin_manager.admin.login_required
def signout():
	admin_manager.signout()

	return redirect(url_for('admin_routes.home'), code=302)


@admin_view.route('/users/view/', methods=['GET'])
@admin_manager.admin.login_required
def users_view():
	admin_manager.admin.set_session(session, g)

	id = int(admin_manager.admin.uid())
	admin = admin_manager.get(id)
	myusers = admin_manager.getUsersList()

	return render_template('admin/users.html', g=g, admin=admin, users=myusers)



@admin_view.route('/books/', methods=['GET'])
@admin_manager.admin.login_required
def books():
	admin_manager.admin.set_session(session, g)

	id = int(admin_manager.admin.uid())
	admin = admin_manager.get(id)
	mybooks = book_manager.list(availability=0)

	return render_template('admin/books/views.html', g=g, books=mybooks, admin=admin)

@admin_view.route('/books/<int:id>')
@admin_manager.admin.login_required
def view_book(id):
	admin_manager.admin.set_session(session, g)

	if id != None:
		b = book_manager.getBook(id)
		users = user_manager.getUsersByBook(id)

		print('----------------------------')
		print(users)
		
		if b and len(b) <1:
			return render_template('books/book_view.html', error="No book found!")

		return render_template("admin/books/book_view.html", books=b, books_owners=users, g=g)


@admin_view.route('/books/add', methods=['GET', 'POST'])
@admin_manager.admin.login_required
def book_add():
	admin_manager.admin.set_session(session, g)
	
	if request.method == 'POST':
		name = request.form.get('name')
		author = request.form.get('author')
		edition = request.form.get('edition')
		count = request.form.get('count')
		availability = int('availability' in request.form)
		desc = request.form.get('desc')

		# Ensure all required fields are filled
		if not name or not author or not edition or not count or not desc:
			flash('Please fill out all required fields', 'danger')
			return redirect(url_for('admin_routes.book_add'))

		book_info = {
			'name': name,
			'author': author,
			'edition': edition,
			'count': count,
			'availabilityv': availability,
			'desc': desc
		}

		book_manager.addBook(book_info)
		return redirect(url_for('admin_routes.books'))

	return render_template("admin/books/add.html", g=g)




@admin_view.route('/books/delete/<int:id>', methods=['GET'])
@admin_manager.admin.login_required
def book_delete(id):
	id = int(id)

	if id is not None:
		book_manager.delete(id)
	
	return redirect('/admin/books/')


@admin_view.route('/books/search', methods=['GET'])
def search():
	admin_manager.admin.set_session(session, g)

	if "keyword" not in request.args:
		return render_template("books/view.html")

	keyword = request.args["keyword"]

	if len(keyword)<1:
		return redirect('/admin/books')

	id = int(admin_manager.admin.uid())
	admin = admin_manager.get(id)

	d=book_manager.search(keyword, 0)

	if len(d) >0:
		return render_template("admin/books/views.html", search=True, books=d, count=len(d), keyword=escape(keyword), g=g, admin=admin)

	return render_template('admin/books/views.html', error="No books found!", keyword=escape(keyword))



@admin_view.route('/books/edit/<int:id>', methods=['GET', 'POST'])
@admin_manager.admin.login_required
def book_edit(id):
    admin_manager.admin.set_session(session, g)
    
    # Handle POST request for form submission
    if request.method == 'POST':
        title = request.form.get('title')
        qty = request.form.get('qty')
        available = int('available' in request.form)
        description = request.form.get('desc')

        # Ensure all required fields are filled
        if not title or not qty:
            flash('Please fill out all required fields', 'danger')
            return redirect(url_for('admin_routes.book_edit', id=id))
        
        
        book_manager.updateBook( id, title, qty, available, description)
        return redirect(url_for('admin_routes.books'))

		
    
    # Handle GET request to display edit form
    if id is not None:
        b = book_manager.getBook(id)

        if b is None or len(b) < 1:
            return render_template('admin/books/edit.html', error="No book found!")

        return render_template("admin/books/edit.html", book=b, g=g)
    
    return redirect('admin/books')

routes/book.py
from flask import Blueprint, g, escape, session, redirect, render_template, request, jsonify, Response
from app import DAO

from Controllers.UserManager import UserManager
from Controllers.BookManager import BookManager

book_view = Blueprint('book_routes', __name__, template_folder='/templates')

book_manager = BookManager(DAO)
user_manager = UserManager(DAO)



@book_view.route('/', defaults={'id': None})
@book_view.route('/<int:id>')
def home(id):
	user_manager.user.set_session(session, g)

	if id != None:
		b = book_manager.getBook(id)

		print('----------------------------')
		print(b)

		user_books={}
		if user_manager.user.isLoggedIn():
			user_books = book_manager.getReserverdBooksByUser(user_id=user_manager.user.uid())['user_books'].split(',')
		
		if b and len(b) <1:
			return render_template('book_view.html', error="No book found!")

		return render_template("book_view.html", books=b, g=g, user_books=user_books)
	else:
		b = book_manager.list()

		user_books=[]
		if user_manager.user.isLoggedIn():
			reserved_books = book_manager.getReserverdBooksByUser(user_id=user_manager.user.uid())
			
			if reserved_books is not None:
				user_books = reserved_books['user_books'].split(',')
		
		print("---------------------------------------")
		print(user_books)

		if b and len(b) <1:
			return render_template('books.html', error="No books found!")
	
		return render_template("books.html", books=b, g=g, user_books=user_books)


	return render_template("books.html", books=b, g=g)


@book_view.route('/add/<id>', methods=['GET'])
@user_manager.user.login_required
def add(id):
	user_id = user_manager.user.uid()
	book_manager.reserve(user_id, id)

	b = book_manager.list()
	user_manager.user.set_session(session, g)
	
	return render_template("books.html", msg="Book reserved", books=b, g=g)


@book_view.route('/search', methods=['GET'])
def search():
	user_manager.user.set_session(session, g)

	if "keyword" not in request.args:
		return render_template("search.html")

	keyword = request.args["keyword"]

	if len(keyword)<1:
		return redirect('/books')

	d=book_manager.search(keyword)

	if len(d) >0:
		return render_template("books.html", search=True, books=d, count=len(d), keyword=escape(keyword), g=g)

	return render_template('books.html', error="No books found!", keyword=escape(keyword))

routes/user.py
from flask import Blueprint, g, escape, session, redirect, render_template, request, jsonify, Response, flash,url_for
from app import DAO  # Data object model that has been initialized with the app 
from Misc.functions import *

from Controllers.UserManager import UserManager


#  Blueprint in Flask is a way to organize your application into modular components
# A new Blueprint instance named user_view is created.
# This blueprint is associated with the name 'user_routes'.
# The __name__ variable helps Flask to know where this blueprint is defined.
# The template_folder='/templates' argument tells Flask to look for templates in the /templates directory when rendering views associated with this blueprint.
user_view = Blueprint('user_routes', __name__, template_folder='/templates')  

user_manager = UserManager(DAO)

@user_view.route('/', methods=['GET'])
def home():
	g.bg = 1

	user_manager.user.set_session(session, g)
	print(g.user)

	return render_template('home.html', g=g)


@user_view.route('/signin', methods=['GET', 'POST'])
@user_manager.user.redirect_if_login
def signin():
	if request.method == 'POST':
		_form = request.form
		email = str(_form["email"])
		password = str(_form["password"])

		if len(email)<1 or len(password)<1:
			return render_template('signin.html', error="Email and password are required")

		d = user_manager.signin(email, hash(password))

		if d and len(d)>0:
			session['user'] = int(d['id'])

			return redirect("/")

		return render_template('signin.html', error="Email or password incorrect")


	return render_template('signin.html')


@user_view.route('/signup', methods=['GET', 'POST'])
@user_manager.user.redirect_if_login
def signup():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')
        bio = request.form.get('bio')
        mobile = request.form.get('mobile')

        if len(name) < 1 or len(email) < 1 or len(password) < 1 or len(bio) < 1 or len(mobile) < 1:
            return render_template('signup.html', error="All fields are required")

        new_user = user_manager.signup(name, email, hash(password), bio, mobile)

        if new_user == "already_exists":
            return render_template('signup.html', error="User already exists with this email")

        return render_template('signup.html', msg="You've been registered!")

    return render_template('signin.html')


@user_view.route('/signout/', methods=['GET'])
@user_manager.user.login_required
def signout():
	user_manager.signout()

	return redirect("/", code=302)

@user_view.route('/user/', methods=['GET'])
@user_manager.user.login_required
def show_user(id=None):
	user_manager.user.set_session(session, g)
	
	if id is None:
		id = int(user_manager.user.uid())

	d = user_manager.get(id)
	mybooks = user_manager.getBooksList(id)

	return render_template("profile.html", user=d, books=mybooks, g=g)

@user_view.route('/user/', methods=['POST'])
@user_manager.user.login_required
def update():
	user_manager.user.set_session(session, g)
	
	_form = request.form
	name = str(_form["name"])
	email = str(_form["email"])
	password = str(_form["password"])
	bio = str(_form["bio"])

	user_manager.update(name, email, hash(password), bio, user_manager.user.uid())

	flash('Your info has been updated!')
	return redirect(url_for('user_routes.show_user'))

templates/shared/admin_layout.html
<html>
<!-- What the page is called in the tab bar  -->
<!-- We will add out stylsheet here later -->
  <!-- admin_Layout.html -->
<head>
	{%block head %}
	<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

	 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<!-- JavaScript Bundle with Popper -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="/static/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/style.css" />
    {% endblock %}
</head>
<!-- Put some text on the page -->
<body {{"class=home" if g and g.bg==1 else ""}}>
	<div class="container-fluid">
		<div class="navbar justify-content-end">
			<ul class="nav">
			  {% if g and g.user%}
				  <li class="nav-item">
				    <a class="nav-link active" href={{url_for('admin_routes.home')}}>Home</a>
				  </li>
				  <li class="nav-item dropdown">
				    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Manage Books</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href={{url_for('admin_routes.books')}}><i class="bi bi-view-list"></i> View Books</a>
					  <a class="dropdown-item" href={{url_for('admin_routes.book_add')}}><i class="bi bi-journal-plus"></i> Add Book</a>
					</div>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('admin_routes.users_view')}}>Manage Users</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link active" href={{url_for('admin_routes.signout')}}>Sign out</a>
				  </li>
				  <!-- <li class="nav-item">
				    <a class="nav-link" href="/user/">Profile</a>
				  </li> -->
				  {% else %}
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('admin_routes.signin')}}>Signin</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('admin_routes.signup')}}>Signup</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('user_routes.home')}}>User</a>
				  </li>
			  {% endif %}
			</ul>
		</div>


		{%block content %}{% endblock %}
	</div>
</body>
</html>

templates/shared/layout.html
<html>
<!-- What the page is called in the tab bar  -->
<!-- We will add out stylsheet here later -->
 <!-- Layout.html -->
<head>
	{%block head %}
	<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
	
    <link rel="stylesheet" href="/static/style.css" />
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<!-- Put some text on the page -->
<body {{"class=home" if g and g.bg==1 else ""}}>
	<div class="container-fluid">
		<div class="navbar justify-content-end mb-5">
			<ul class="nav">
			  <li class="nav-item">
			    <a class="nav-link active" href="/">Home</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" href={{url_for('book_routes.home')}}>Books</a>
			  </li>
			  {% if g and g.user %}
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('user_routes.show_user')}}>Profile</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('user_routes.signout')}}>Signout</a>
				  </li>
			  {% else %}
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('user_routes.signin')}}>Signin</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('user_routes.signup')}}>Signup</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href={{url_for('admin_routes.home')}}>Admin</a>
				  </li>
			  {% endif %}
			</ul>
		</div>

		{%block content %}{% endblock %}
	</div>
</body>
</html>